idf_component_register(
    SRCS
        "main.c"
        "thp_sources.c"
        "thp_wifi.c"
        "thp_time.c"
        "thp_local.c"
        "thp_queue.c"
        "thp_report.c"
        "thp_ble.c"
        "thp_sched.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        sht40
        bmp280
        atc_ble
        esp_driver_i2c
        esp_driver_gpio
        esp_timer
        esp_system
        esp_event
        esp_netif
        esp_wifi
        nvs_flash
        esp_http_client
        mbedtls
        lwip
        freertos
        log
        bt
)
